CREATE TABLE IF NOT EXISTS vocabulary_words (
  id INT PRIMARY KEY AUTO_INCREMENT,
  word VARCHAR(64) NOT NULL,
  phonetic VARCHAR(128) DEFAULT NULL,
  meaning_zh VARCHAR(512) NOT NULL,
  example_en VARCHAR(512) DEFAULT NULL,
  example_zh VARCHAR(512) DEFAULT NULL,
  tags VARCHAR(128) NOT NULL DEFAULT 'kaoyan',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_vocab_word (word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vocabulary_phrases (
  id INT PRIMARY KEY AUTO_INCREMENT,
  kind VARCHAR(16) NOT NULL DEFAULT 'phrase',
  title VARCHAR(120) DEFAULT NULL,
  phrase_en TEXT NOT NULL,
  meaning_zh TEXT NOT NULL,
  content_hash CHAR(32) NOT NULL,
  tags VARCHAR(128) NOT NULL DEFAULT 'kaoyan',
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_vocab_phrase_hash (content_hash),
  KEY idx_vocab_phrase_kind (kind, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
